#### Katrina Johnson - DSB Unit 2.4.2 Drill: Prepare the Data

## DRILL: Prepare the Data
Download the Excel file here on crime data in New York State in 2013, provided by the FBI: UCR (Thinkful mirror).

Prepare this data to model with multivariable regression (including data cleaning if necessary) according to this specification:

### 𝑃𝑟𝑜𝑝𝑒𝑟𝑡𝑦𝑐𝑟𝑖𝑚𝑒=𝛼+𝑃𝑜𝑝𝑢𝑙𝑎𝑡𝑖𝑜𝑛+𝑃𝑜𝑝𝑢𝑙𝑎𝑡𝑖𝑜𝑛2+𝑀𝑢𝑟𝑑𝑒𝑟+𝑅𝑜𝑏𝑏𝑒𝑟𝑦
 
The 'population' variable is already set for you, but you will need to create the last three features. Robbery and Murder are currently continuous variables. For this model, please use these variables to create categorical features where values greater than 0 are coded 1, and values equal to 0 are coded 0. You'll use this data and model in a later assignment- for now, just write the code you need to get the data ready. Don't forget basic data cleaning procedures, either! Do some graphing to see if there are any anomalous cases, and decide how you want to deal with them.

In [95]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from sklearn import linear_model
%matplotlib inline
pd.options.display.float_format = '{:.3f}'.format

# Suppress annoying harmless error.
import warnings
warnings.filterwarnings(action="ignore", module="scipy", message="^internal gelsd")

In [96]:
df = pd.read_excel('table_8_offenses_known_to_law_enforcement_new_york_by_city_2013.xls')
df

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NEW YORK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"by City, 2013",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,City,Population,Violent\ncrime,Murder and\nnonnegligent\nmanslaughter,Rape\n(revised\ndefinition)1,Rape\n(legacy\ndefinition)2,Robbery,Aggravated\nassault,Property\ncrime,Burglary,Larceny-\ntheft,Motor\nvehicle\ntheft,Arson3
4,Adams Village,1861,0,0,NaN,0,0,0,12,2,10,0,0
5,Addison Town and Village,2577,3,0,NaN,0,0,3,24,3,20,1,0
6,Akron Village,2846,3,0,NaN,0,0,3,16,1,15,0,0
7,Albany,97956,791,8,NaN,30,227,526,4090,705,3243,142,NaN
8,Albion Village,6388,23,0,NaN,3,4,16,223,53,165,5,NaN
9,Alfred Village,4089,5,0,NaN,0,3,2,46,10,36,0,NaN
10,Allegany Village,1781,3,0,NaN,0,0,3,10,0,10,0,0
11,Amherst Town,118296,107,1,NaN,7,31,68,2118,204,1882,32,3
12,Amityville Village,9519,9,0,NaN,2,4,3,210,16,188,6,1
13,Amsterdam,18182,30,0,NaN,0,12,18,405,99,291,15,0
14,Arcade Village,2053,0,0,NaN,0,0,0,39,3,35,1,0
15,Ardsley Village,4523,5,0,NaN,0,3,2,33,4,28,1,0
16,Asharoken Village,658,0,0,NaN,0,0,0,2,0,2,0,0
17,Attica Village,2522,2,0,NaN,0,0,2,5,0,4,1,0
18,Auburn,27270,96,1,NaN,20,22,53,859,132,721,6,NaN
19,Avon Village,3333,1,0,NaN,0,1,0,25,3,20,2,NaN
20,Baldwinsville Village,7473,5,0,NaN,0,1,4,88,10,77,1,0
21,Ballston Spa Village,5418,8,0,NaN,0,3,5,94,16,78,0,1
22,Batavia,15374,57,0,NaN,7,13,37,559,103,454,2,NaN
23,Bath Village,5733,15,0,NaN,1,3,11,191,32,157,2,2
24,Bedford Town,17627,5,0,NaN,0,1,4,156,26,127,3,NaN
25,Bethlehem Town,34243,13,0,NaN,0,3,10,442,50,388,4,NaN
26,Binghamton,46304,284,3,NaN,19,101,161,2349,525,1767,57,NaN
27,Black River,1410,0,0,NaN,0,0,0,14,2,12,0,0
28,Blooming Grove Town,12001,8,0,NaN,1,0,7,99,20,72,7,NaN
29,Bolivar Village,1022,1,0,NaN,0,0,1,4,2,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Utica,61686,361,7,NaN,27,102,225,2528,449,1997,82,NaN
326,Vestal Town,27980,16,0,NaN,2,6,8,571,39,523,9,NaN
327,Walden Village,6887,18,1,NaN,2,1,14,142,13,124,5,NaN
328,Wallkill Town,27940,40,0,NaN,3,16,21,767,91,650,26,1
329,Walton Village,3012,6,0,NaN,1,0,5,68,18,50,0,NaN
330,Warsaw Village,3453,6,0,NaN,1,0,5,78,5,73,0,0
331,Washingtonville Village,5828,2,0,NaN,0,1,1,58,5,51,2,0
332,Waterford Town and Village,8392,4,0,NaN,0,0,4,59,6,52,1,0
333,Waterloo Village,5175,11,0,NaN,0,3,8,194,23,169,2,NaN
334,Watertown,28179,109,0,NaN,12,16,81,1165,169,953,43,NaN
335,Watervliet,10245,26,1,NaN,3,11,11,242,58,163,21,NaN
336,Watkins Glen Village,1862,6,0,NaN,0,0,6,92,10,80,2,NaN
337,Waverly Village,4337,5,0,NaN,0,1,4,54,9,41,4,NaN
338,Webster Town and Village,43777,21,0,NaN,2,3,16,469,101,361,7,NaN
339,Weedsport Village,1797,0,0,NaN,0,0,0,25,5,20,0,0
340,Wellsville Village,4574,11,0,NaN,1,0,10,164,32,129,3,1
341,Westhampton Beach Village,1732,2,0,NaN,0,0,2,44,4,37,3,0
342,West Seneca Town,44821,35,1,NaN,1,9,24,896,166,710,20,0
343,Whitehall Village,2604,6,0,NaN,0,0,6,62,12,49,1,NaN
344,White Plains,57559,78,1,NaN,3,28,46,1232,77,1134,21,NaN
345,Whitesboro Village,3733,4,0,NaN,0,0,4,36,14,21,1,0
346,Whitestown Town,9141,0,0,NaN,0,0,0,77,13,61,3,0
347,Woodbury Town,10685,3,0,NaN,0,2,1,541,9,529,3,NaN
348,Woodridge Village,829,7,0,NaN,0,0,7,17,8,9,0,0
349,Woodstock Town,5931,2,0,NaN,0,0,2,58,13,45,0,NaN
350,Yonkers,199134,1036,6,NaN,25,390,615,2368,470,1662,236,10
351,Yorktown Town,36643,15,0,NaN,0,2,13,334,45,287,2,NaN
352,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
354,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [97]:
df.iloc[3]

Table 8                                          City
Unnamed: 1                                 Population
Unnamed: 2                             Violent\ncrime
Unnamed: 3     Murder and\nnonnegligent\nmanslaughter
Unnamed: 4               Rape\n(revised\ndefinition)1
Unnamed: 5                Rape\n(legacy\ndefinition)2
Unnamed: 6                                    Robbery
Unnamed: 7                        Aggravated\nassault
Unnamed: 8                            Property\ncrime
Unnamed: 9                                   Burglary
Unnamed: 10                           Larceny-\ntheft
Unnamed: 11                     Motor\nvehicle\ntheft
Unnamed: 12                                    Arson3
Name: 3, dtype: object

In [98]:
df.columns = ['City', 'Population', 'Violent crime', 'Murder and non negligent manslaughter', 'Rape (revised definition) 1',
              'Rape (legacy definition) 2', 'Robbery', 'Aggravated assault', 'Property crime', 'Burglary', 'Larceny theft', 
              'Motor vehicle theft', 'Arson 3']

df

,City,Population,Violent crime,Murder and non negligent manslaughter,Rape (revised definition) 1,Rape (legacy definition) 2,Robbery,Aggravated assault,Property crime,Burglary,Larceny theft,Motor vehicle theft,Arson 3
0,NEW YORK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"by City, 2013",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,City,Population,Violent\ncrime,Murder and\nnonnegligent\nmanslaughter,Rape\n(revised\ndefinition)1,Rape\n(legacy\ndefinition)2,Robbery,Aggravated\nassault,Property\ncrime,Burglary,Larceny-\ntheft,Motor\nvehicle\ntheft,Arson3
4,Adams Village,1861,0,0,NaN,0,0,0,12,2,10,0,0
5,Addison Town and Village,2577,3,0,NaN,0,0,3,24,3,20,1,0
6,Akron Village,2846,3,0,NaN,0,0,3,16,1,15,0,0
7,Albany,97956,791,8,NaN,30,227,526,4090,705,3243,142,NaN
8,Albion Village,6388,23,0,NaN,3,4,16,223,53,165,5,NaN
9,Alfred Village,4089,5,0,NaN,0,3,2,46,10,36,0,NaN
10,Allegany Village,1781,3,0,NaN,0,0,3,10,0,10,0,0
11,Amherst Town,118296,107,1,NaN,7,31,68,2118,204,1882,32,3
12,Amityville Village,9519,9,0,NaN,2,4,3,210,16,188,6,1
13,Amsterdam,18182,30,0,NaN,0,12,18,405,99,291,15,0
14,Arcade Village,2053,0,0,NaN,0,0,0,39,3,35,1,0
15,Ardsley Village,4523,5,0,NaN,0,3,2,33,4,28,1,0
16,Asharoken Village,658,0,0,NaN,0,0,0,2,0,2,0,0
17,Attica Village,2522,2,0,NaN,0,0,2,5,0,4,1,0
18,Auburn,27270,96,1,NaN,20,22,53,859,132,721,6,NaN
19,Avon Village,3333,1,0,NaN,0,1,0,25,3,20,2,NaN
20,Baldwinsville Village,7473,5,0,NaN,0,1,4,88,10,77,1,0
21,Ballston Spa Village,5418,8,0,NaN,0,3,5,94,16,78,0,1
22,Batavia,15374,57,0,NaN,7,13,37,559,103,454,2,NaN
23,Bath Village,5733,15,0,NaN,1,3,11,191,32,157,2,2
24,Bedford Town,17627,5,0,NaN,0,1,4,156,26,127,3,NaN
25,Bethlehem Town,34243,13,0,NaN,0,3,10,442,50,388,4,NaN
26,Binghamton,46304,284,3,NaN,19,101,161,2349,525,1767,57,NaN
27,Black River,1410,0,0,NaN,0,0,0,14,2,12,0,0
28,Blooming Grove Town,12001,8,0,NaN,1,0,7,99,20,72,7,NaN
29,Bolivar Village,1022,1,0,NaN,0,0,1,4,2,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Utica,61686,361,7,NaN,27,102,225,2528,449,1997,82,NaN
326,Vestal Town,27980,16,0,NaN,2,6,8,571,39,523,9,NaN
327,Walden Village,6887,18,1,NaN,2,1,14,142,13,124,5,NaN
328,Wallkill Town,27940,40,0,NaN,3,16,21,767,91,650,26,1
329,Walton Village,3012,6,0,NaN,1,0,5,68,18,50,0,NaN
330,Warsaw Village,3453,6,0,NaN,1,0,5,78,5,73,0,0
331,Washingtonville Village,5828,2,0,NaN,0,1,1,58,5,51,2,0
332,Waterford Town and Village,8392,4,0,NaN,0,0,4,59,6,52,1,0
333,Waterloo Village,5175,11,0,NaN,0,3,8,194,23,169,2,NaN
334,Watertown,28179,109,0,NaN,12,16,81,1165,169,953,43,NaN
335,Watervliet,10245,26,1,NaN,3,11,11,242,58,163,21,NaN
336,Watkins Glen Village,1862,6,0,NaN,0,0,6,92,10,80,2,NaN
337,Waverly Village,4337,5,0,NaN,0,1,4,54,9,41,4,NaN
338,Webster Town and Village,43777,21,0,NaN,2,3,16,469,101,361,7,NaN
339,Weedsport Village,1797,0,0,NaN,0,0,0,25,5,20,0,0
340,Wellsville Village,4574,11,0,NaN,1,0,10,164,32,129,3,1
341,Westhampton Beach Village,1732,2,0,NaN,0,0,2,44,4,37,3,0
342,West Seneca Town,44821,35,1,NaN,1,9,24,896,166,710,20,0
343,Whitehall Village,2604,6,0,NaN,0,0,6,62,12,49,1,NaN
344,White Plains,57559,78,1,NaN,3,28,46,1232,77,1134,21,NaN
345,Whitesboro Village,3733,4,0,NaN,0,0,4,36,14,21,1,0
346,Whitestown Town,9141,0,0,NaN,0,0,0,77,13,61,3,0
347,Woodbury Town,10685,3,0,NaN,0,2,1,541,9,529,3,NaN
348,Woodridge Village,829,7,0,NaN,0,0,7,17,8,9,0,0
349,Woodstock Town,5931,2,0,NaN,0,0,2,58,13,45,0,NaN
350,Yonkers,199134,1036,6,NaN,25,390,615,2368,470,1662,236,10
351,Yorktown Town,36643,15,0,NaN,0,2,13,334,45,287,2,NaN
352,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
354,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [99]:
df = df.drop(0)
df = df.drop(1)
df = df.drop(2)
df = df.drop(3)
df = df.drop(352)
df = df.drop(353)
df = df.drop(354)

df

,City,Population,Violent crime,Murder and non negligent manslaughter,Rape (revised definition) 1,Rape (legacy definition) 2,Robbery,Aggravated assault,Property crime,Burglary,Larceny theft,Motor vehicle theft,Arson 3
4,Adams Village,1861,0,0,NaN,0,0,0,12,2,10,0,0
5,Addison Town and Village,2577,3,0,NaN,0,0,3,24,3,20,1,0
6,Akron Village,2846,3,0,NaN,0,0,3,16,1,15,0,0
7,Albany,97956,791,8,NaN,30,227,526,4090,705,3243,142,NaN
8,Albion Village,6388,23,0,NaN,3,4,16,223,53,165,5,NaN
9,Alfred Village,4089,5,0,NaN,0,3,2,46,10,36,0,NaN
10,Allegany Village,1781,3,0,NaN,0,0,3,10,0,10,0,0
11,Amherst Town,118296,107,1,NaN,7,31,68,2118,204,1882,32,3
12,Amityville Village,9519,9,0,NaN,2,4,3,210,16,188,6,1
13,Amsterdam,18182,30,0,NaN,0,12,18,405,99,291,15,0
14,Arcade Village,2053,0,0,NaN,0,0,0,39,3,35,1,0
15,Ardsley Village,4523,5,0,NaN,0,3,2,33,4,28,1,0
16,Asharoken Village,658,0,0,NaN,0,0,0,2,0,2,0,0
17,Attica Village,2522,2,0,NaN,0,0,2,5,0,4,1,0
18,Auburn,27270,96,1,NaN,20,22,53,859,132,721,6,NaN
19,Avon Village,3333,1,0,NaN,0,1,0,25,3,20,2,NaN
20,Baldwinsville Village,7473,5,0,NaN,0,1,4,88,10,77,1,0
21,Ballston Spa Village,5418,8,0,NaN,0,3,5,94,16,78,0,1
22,Batavia,15374,57,0,NaN,7,13,37,559,103,454,2,NaN
23,Bath Village,5733,15,0,NaN,1,3,11,191,32,157,2,2
24,Bedford Town,17627,5,0,NaN,0,1,4,156,26,127,3,NaN
25,Bethlehem Town,34243,13,0,NaN,0,3,10,442,50,388,4,NaN
26,Binghamton,46304,284,3,NaN,19,101,161,2349,525,1767,57,NaN
27,Black River,1410,0,0,NaN,0,0,0,14,2,12,0,0
28,Blooming Grove Town,12001,8,0,NaN,1,0,7,99,20,72,7,NaN
29,Bolivar Village,1022,1,0,NaN,0,0,1,4,2,2,0,0
30,Bolton Town,2325,2,0,NaN,0,0,2,24,4,20,0,0
31,Boonville Village,2054,1,0,NaN,0,0,1,20,6,14,0,0
32,Brant Town,2065,4,0,NaN,0,1,3,31,9,20,2,0
33,Brewster,2358,0,0,NaN,0,0,0,13,3,10,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,Tupper Lake Village,3642,3,0,NaN,0,0,3,83,22,59,2,NaN
323,Tuxedo Park Village,615,0,0,NaN,0,0,0,0,0,0,0,0
324,Ulster Town,12195,14,0,NaN,3,2,9,437,25,410,2,NaN
325,Utica,61686,361,7,NaN,27,102,225,2528,449,1997,82,NaN
326,Vestal Town,27980,16,0,NaN,2,6,8,571,39,523,9,NaN
327,Walden Village,6887,18,1,NaN,2,1,14,142,13,124,5,NaN
328,Wallkill Town,27940,40,0,NaN,3,16,21,767,91,650,26,1
329,Walton Village,3012,6,0,NaN,1,0,5,68,18,50,0,NaN
330,Warsaw Village,3453,6,0,NaN,1,0,5,78,5,73,0,0
331,Washingtonville Village,5828,2,0,NaN,0,1,1,58,5,51,2,0
332,Waterford Town and Village,8392,4,0,NaN,0,0,4,59,6,52,1,0
333,Waterloo Village,5175,11,0,NaN,0,3,8,194,23,169,2,NaN
334,Watertown,28179,109,0,NaN,12,16,81,1165,169,953,43,NaN
335,Watervliet,10245,26,1,NaN,3,11,11,242,58,163,21,NaN
336,Watkins Glen Village,1862,6,0,NaN,0,0,6,92,10,80,2,NaN
337,Waverly Village,4337,5,0,NaN,0,1,4,54,9,41,4,NaN
338,Webster Town and Village,43777,21,0,NaN,2,3,16,469,101,361,7,NaN
339,Weedsport Village,1797,0,0,NaN,0,0,0,25,5,20,0,0
340,Wellsville Village,4574,11,0,NaN,1,0,10,164,32,129,3,1
341,Westhampton Beach Village,1732,2,0,NaN,0,0,2,44,4,37,3,0
342,West Seneca Town,44821,35,1,NaN,1,9,24,896,166,710,20,0
343,Whitehall Village,2604,6,0,NaN,0,0,6,62,12,49,1,NaN
344,White Plains,57559,78,1,NaN,3,28,46,1232,77,1134,21,NaN
345,Whitesboro Village,3733,4,0,NaN,0,0,4,36,14,21,1,0
346,Whitestown Town,9141,0,0,NaN,0,0,0,77,13,61,3,0
347,Woodbury Town,10685,3,0,NaN,0,2,1,541,9,529,3,NaN
348,Woodridge Village,829,7,0,NaN,0,0,7,17,8,9,0,0
349,Woodstock Town,5931,2,0,NaN,0,0,2,58,13,45,0,NaN
350,Yonkers,199134,1036,6,NaN,25,390,615,2368,470,1662,236,10
351,Yorktown Town,36643,15,0,NaN,0,2,13,334,45,287,2,NaN

#df.findall({NaN}).any(axis=1).sum()
index = df['Rape (revised definition) 1'].index[df['Rape (revised definition) 1'].apply(np.isnan)]
index

In [100]:
df = df.replace({None: ''})

df

,City,Population,Violent crime,Murder and non negligent manslaughter,Rape (revised definition) 1,Rape (legacy definition) 2,Robbery,Aggravated assault,Property crime,Burglary,Larceny theft,Motor vehicle theft,Arson 3
4,Adams Village,1861,0,0,,0,0,0,12,2,10,0,0
5,Addison Town and Village,2577,3,0,,0,0,3,24,3,20,1,0
6,Akron Village,2846,3,0,,0,0,3,16,1,15,0,0
7,Albany,97956,791,8,,30,227,526,4090,705,3243,142,
8,Albion Village,6388,23,0,,3,4,16,223,53,165,5,
9,Alfred Village,4089,5,0,,0,3,2,46,10,36,0,
10,Allegany Village,1781,3,0,,0,0,3,10,0,10,0,0
11,Amherst Town,118296,107,1,,7,31,68,2118,204,1882,32,3
12,Amityville Village,9519,9,0,,2,4,3,210,16,188,6,1
13,Amsterdam,18182,30,0,,0,12,18,405,99,291,15,0
14,Arcade Village,2053,0,0,,0,0,0,39,3,35,1,0
15,Ardsley Village,4523,5,0,,0,3,2,33,4,28,1,0
16,Asharoken Village,658,0,0,,0,0,0,2,0,2,0,0
17,Attica Village,2522,2,0,,0,0,2,5,0,4,1,0
18,Auburn,27270,96,1,,20,22,53,859,132,721,6,
19,Avon Village,3333,1,0,,0,1,0,25,3,20,2,
20,Baldwinsville Village,7473,5,0,,0,1,4,88,10,77,1,0
21,Ballston Spa Village,5418,8,0,,0,3,5,94,16,78,0,1
22,Batavia,15374,57,0,,7,13,37,559,103,454,2,
23,Bath Village,5733,15,0,,1,3,11,191,32,157,2,2
24,Bedford Town,17627,5,0,,0,1,4,156,26,127,3,
25,Bethlehem Town,34243,13,0,,0,3,10,442,50,388,4,
26,Binghamton,46304,284,3,,19,101,161,2349,525,1767,57,
27,Black River,1410,0,0,,0,0,0,14,2,12,0,0
28,Blooming Grove Town,12001,8,0,,1,0,7,99,20,72,7,
29,Bolivar Village,1022,1,0,,0,0,1,4,2,2,0,0
30,Bolton Town,2325,2,0,,0,0,2,24,4,20,0,0
31,Boonville Village,2054,1,0,,0,0,1,20,6,14,0,0
32,Brant Town,2065,4,0,,0,1,3,31,9,20,2,0
33,Brewster,2358,0,0,,0,0,0,13,3,10,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,Tupper Lake Village,3642,3,0,,0,0,3,83,22,59,2,
323,Tuxedo Park Village,615,0,0,,0,0,0,0,0,0,0,0
324,Ulster Town,12195,14,0,,3,2,9,437,25,410,2,
325,Utica,61686,361,7,,27,102,225,2528,449,1997,82,
326,Vestal Town,27980,16,0,,2,6,8,571,39,523,9,
327,Walden Village,6887,18,1,,2,1,14,142,13,124,5,
328,Wallkill Town,27940,40,0,,3,16,21,767,91,650,26,1
329,Walton Village,3012,6,0,,1,0,5,68,18,50,0,
330,Warsaw Village,3453,6,0,,1,0,5,78,5,73,0,0
331,Washingtonville Village,5828,2,0,,0,1,1,58,5,51,2,0
332,Waterford Town and Village,8392,4,0,,0,0,4,59,6,52,1,0
333,Waterloo Village,5175,11,0,,0,3,8,194,23,169,2,
334,Watertown,28179,109,0,,12,16,81,1165,169,953,43,
335,Watervliet,10245,26,1,,3,11,11,242,58,163,21,
336,Watkins Glen Village,1862,6,0,,0,0,6,92,10,80,2,
337,Waverly Village,4337,5,0,,0,1,4,54,9,41,4,
338,Webster Town and Village,43777,21,0,,2,3,16,469,101,361,7,
339,Weedsport Village,1797,0,0,,0,0,0,25,5,20,0,0
340,Wellsville Village,4574,11,0,,1,0,10,164,32,129,3,1
341,Westhampton Beach Village,1732,2,0,,0,0,2,44,4,37,3,0
342,West Seneca Town,44821,35,1,,1,9,24,896,166,710,20,0
343,Whitehall Village,2604,6,0,,0,0,6,62,12,49,1,
344,White Plains,57559,78,1,,3,28,46,1232,77,1134,21,
345,Whitesboro Village,3733,4,0,,0,0,4,36,14,21,1,0
346,Whitestown Town,9141,0,0,,0,0,0,77,13,61,3,0
347,Woodbury Town,10685,3,0,,0,2,1,541,9,529,3,
348,Woodridge Village,829,7,0,,0,0,7,17,8,9,0,0
349,Woodstock Town,5931,2,0,,0,0,2,58,13,45,0,
350,Yonkers,199134,1036,6,,25,390,615,2368,470,1662,236,10
351,Yorktown Town,36643,15,0,,0,2,13,334,45,287,2,

In [101]:
#df.insert(6, 'Robbery binary', '')
#df.insert(10, 'Burglary binary', '')

#df

In [102]:
robbery_binary = []
x = df.loc[df['Robbery']]
#Note: for loops do not need a return at the end. Only functions need to end with a return statement.

for item in df.Robbery:
    if item > 0:
        robbery_binary.append(1)
    else: 
        robbery_binary.append(0)
        
print(robbery_binary)

[0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1]

/Users/katrinajohnson/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike

In [103]:
#I can now take the list robbery_binary and append it to df['Robbery binary']
df.insert(6, 'Robbery binary', robbery_binary)
df

,City,Population,Violent crime,Murder and non negligent manslaughter,Rape (revised definition) 1,Rape (legacy definition) 2,Robbery binary,Robbery,Aggravated assault,Property crime,Burglary,Larceny theft,Motor vehicle theft,Arson 3
4,Adams Village,1861,0,0,,0,0,0,0,12,2,10,0,0
5,Addison Town and Village,2577,3,0,,0,0,0,3,24,3,20,1,0
6,Akron Village,2846,3,0,,0,0,0,3,16,1,15,0,0
7,Albany,97956,791,8,,30,1,227,526,4090,705,3243,142,
8,Albion Village,6388,23,0,,3,1,4,16,223,53,165,5,
9,Alfred Village,4089,5,0,,0,1,3,2,46,10,36,0,
10,Allegany Village,1781,3,0,,0,0,0,3,10,0,10,0,0
11,Amherst Town,118296,107,1,,7,1,31,68,2118,204,1882,32,3
12,Amityville Village,9519,9,0,,2,1,4,3,210,16,188,6,1
13,Amsterdam,18182,30,0,,0,1,12,18,405,99,291,15,0
14,Arcade Village,2053,0,0,,0,0,0,0,39,3,35,1,0
15,Ardsley Village,4523,5,0,,0,1,3,2,33,4,28,1,0
16,Asharoken Village,658,0,0,,0,0,0,0,2,0,2,0,0
17,Attica Village,2522,2,0,,0,0,0,2,5,0,4,1,0
18,Auburn,27270,96,1,,20,1,22,53,859,132,721,6,
19,Avon Village,3333,1,0,,0,1,1,0,25,3,20,2,
20,Baldwinsville Village,7473,5,0,,0,1,1,4,88,10,77,1,0
21,Ballston Spa Village,5418,8,0,,0,1,3,5,94,16,78,0,1
22,Batavia,15374,57,0,,7,1,13,37,559,103,454,2,
23,Bath Village,5733,15,0,,1,1,3,11,191,32,157,2,2
24,Bedford Town,17627,5,0,,0,1,1,4,156,26,127,3,
25,Bethlehem Town,34243,13,0,,0,1,3,10,442,50,388,4,
26,Binghamton,46304,284,3,,19,1,101,161,2349,525,1767,57,
27,Black River,1410,0,0,,0,0,0,0,14,2,12,0,0
28,Blooming Grove Town,12001,8,0,,1,0,0,7,99,20,72,7,
29,Bolivar Village,1022,1,0,,0,0,0,1,4,2,2,0,0
30,Bolton Town,2325,2,0,,0,0,0,2,24,4,20,0,0
31,Boonville Village,2054,1,0,,0,0,0,1,20,6,14,0,0
32,Brant Town,2065,4,0,,0,1,1,3,31,9,20,2,0
33,Brewster,2358,0,0,,0,0,0,0,13,3,10,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,Tupper Lake Village,3642,3,0,,0,0,0,3,83,22,59,2,
323,Tuxedo Park Village,615,0,0,,0,0,0,0,0,0,0,0,0
324,Ulster Town,12195,14,0,,3,1,2,9,437,25,410,2,
325,Utica,61686,361,7,,27,1,102,225,2528,449,1997,82,
326,Vestal Town,27980,16,0,,2,1,6,8,571,39,523,9,
327,Walden Village,6887,18,1,,2,1,1,14,142,13,124,5,
328,Wallkill Town,27940,40,0,,3,1,16,21,767,91,650,26,1
329,Walton Village,3012,6,0,,1,0,0,5,68,18,50,0,
330,Warsaw Village,3453,6,0,,1,0,0,5,78,5,73,0,0
331,Washingtonville Village,5828,2,0,,0,1,1,1,58,5,51,2,0
332,Waterford Town and Village,8392,4,0,,0,0,0,4,59,6,52,1,0
333,Waterloo Village,5175,11,0,,0,1,3,8,194,23,169,2,
334,Watertown,28179,109,0,,12,1,16,81,1165,169,953,43,
335,Watervliet,10245,26,1,,3,1,11,11,242,58,163,21,
336,Watkins Glen Village,1862,6,0,,0,0,0,6,92,10,80,2,
337,Waverly Village,4337,5,0,,0,1,1,4,54,9,41,4,
338,Webster Town and Village,43777,21,0,,2,1,3,16,469,101,361,7,
339,Weedsport Village,1797,0,0,,0,0,0,0,25,5,20,0,0
340,Wellsville Village,4574,11,0,,1,0,0,10,164,32,129,3,1
341,Westhampton Beach Village,1732,2,0,,0,0,0,2,44,4,37,3,0
342,West Seneca Town,44821,35,1,,1,1,9,24,896,166,710,20,0
343,Whitehall Village,2604,6,0,,0,0,0,6,62,12,49,1,
344,White Plains,57559,78,1,,3,1,28,46,1232,77,1134,21,
345,Whitesboro Village,3733,4,0,,0,0,0,4,36,14,21,1,0
346,Whitestown Town,9141,0,0,,0,0,0,0,77,13,61,3,0
347,Woodbury Town,10685,3,0,,0,1,2,1,541,9,529,3,
348,Woodridge Village,829,7,0,,0,0,0,7,17,8,9,0,0
349,Woodstock Town,5931,2,0,,0,0,0,2,58,13,45,0,
350,Yonkers,199134,1036,6,,25,1,390,615,2368,470,1662,236,10
351,Yorktown Town,36643,15,0,,0,1,2,13,334,45,287,2,

In [104]:
burglary_binary = []
x = df.loc[df['Burglary']]
#Note: for loops do not need a return at the end. Only functions need to end with a return statement.

for item in df.Burglary:
    if item > 0:
        burglary_binary.append(1)
    else: 
        burglary_binary.append(0)
        
print(burglary_binary)

[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

/Users/katrinajohnson/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike

In [105]:
#I can now take the list robbery_binary and append it to df['Robbery binary']
df.insert(10, 'Burglary binary', burglary_binary)
df

,City,Population,Violent crime,Murder and non negligent manslaughter,Rape (revised definition) 1,Rape (legacy definition) 2,Robbery binary,Robbery,Aggravated assault,Property crime,Burglary binary,Burglary,Larceny theft,Motor vehicle theft,Arson 3
4,Adams Village,1861,0,0,,0,0,0,0,12,1,2,10,0,0
5,Addison Town and Village,2577,3,0,,0,0,0,3,24,1,3,20,1,0
6,Akron Village,2846,3,0,,0,0,0,3,16,1,1,15,0,0
7,Albany,97956,791,8,,30,1,227,526,4090,1,705,3243,142,
8,Albion Village,6388,23,0,,3,1,4,16,223,1,53,165,5,
9,Alfred Village,4089,5,0,,0,1,3,2,46,1,10,36,0,
10,Allegany Village,1781,3,0,,0,0,0,3,10,0,0,10,0,0
11,Amherst Town,118296,107,1,,7,1,31,68,2118,1,204,1882,32,3
12,Amityville Village,9519,9,0,,2,1,4,3,210,1,16,188,6,1
13,Amsterdam,18182,30,0,,0,1,12,18,405,1,99,291,15,0
14,Arcade Village,2053,0,0,,0,0,0,0,39,1,3,35,1,0
15,Ardsley Village,4523,5,0,,0,1,3,2,33,1,4,28,1,0
16,Asharoken Village,658,0,0,,0,0,0,0,2,0,0,2,0,0
17,Attica Village,2522,2,0,,0,0,0,2,5,0,0,4,1,0
18,Auburn,27270,96,1,,20,1,22,53,859,1,132,721,6,
19,Avon Village,3333,1,0,,0,1,1,0,25,1,3,20,2,
20,Baldwinsville Village,7473,5,0,,0,1,1,4,88,1,10,77,1,0
21,Ballston Spa Village,5418,8,0,,0,1,3,5,94,1,16,78,0,1
22,Batavia,15374,57,0,,7,1,13,37,559,1,103,454,2,
23,Bath Village,5733,15,0,,1,1,3,11,191,1,32,157,2,2
24,Bedford Town,17627,5,0,,0,1,1,4,156,1,26,127,3,
25,Bethlehem Town,34243,13,0,,0,1,3,10,442,1,50,388,4,
26,Binghamton,46304,284,3,,19,1,101,161,2349,1,525,1767,57,
27,Black River,1410,0,0,,0,0,0,0,14,1,2,12,0,0
28,Blooming Grove Town,12001,8,0,,1,0,0,7,99,1,20,72,7,
29,Bolivar Village,1022,1,0,,0,0,0,1,4,1,2,2,0,0
30,Bolton Town,2325,2,0,,0,0,0,2,24,1,4,20,0,0
31,Boonville Village,2054,1,0,,0,0,0,1,20,1,6,14,0,0
32,Brant Town,2065,4,0,,0,1,1,3,31,1,9,20,2,0
33,Brewster,2358,0,0,,0,0,0,0,13,1,3,10,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,Tupper Lake Village,3642,3,0,,0,0,0,3,83,1,22,59,2,
323,Tuxedo Park Village,615,0,0,,0,0,0,0,0,0,0,0,0,0
324,Ulster Town,12195,14,0,,3,1,2,9,437,1,25,410,2,
325,Utica,61686,361,7,,27,1,102,225,2528,1,449,1997,82,
326,Vestal Town,27980,16,0,,2,1,6,8,571,1,39,523,9,
327,Walden Village,6887,18,1,,2,1,1,14,142,1,13,124,5,
328,Wallkill Town,27940,40,0,,3,1,16,21,767,1,91,650,26,1
329,Walton Village,3012,6,0,,1,0,0,5,68,1,18,50,0,
330,Warsaw Village,3453,6,0,,1,0,0,5,78,1,5,73,0,0
331,Washingtonville Village,5828,2,0,,0,1,1,1,58,1,5,51,2,0
332,Waterford Town and Village,8392,4,0,,0,0,0,4,59,1,6,52,1,0
333,Waterloo Village,5175,11,0,,0,1,3,8,194,1,23,169,2,
334,Watertown,28179,109,0,,12,1,16,81,1165,1,169,953,43,
335,Watervliet,10245,26,1,,3,1,11,11,242,1,58,163,21,
336,Watkins Glen Village,1862,6,0,,0,0,0,6,92,1,10,80,2,
337,Waverly Village,4337,5,0,,0,1,1,4,54,1,9,41,4,
338,Webster Town and Village,43777,21,0,,2,1,3,16,469,1,101,361,7,
339,Weedsport Village,1797,0,0,,0,0,0,0,25,1,5,20,0,0
340,Wellsville Village,4574,11,0,,1,0,0,10,164,1,32,129,3,1
341,Westhampton Beach Village,1732,2,0,,0,0,0,2,44,1,4,37,3,0
342,West Seneca Town,44821,35,1,,1,1,9,24,896,1,166,710,20,0
343,Whitehall Village,2604,6,0,,0,0,0,6,62,1,12,49,1,
344,White Plains,57559,78,1,,3,1,28,46,1232,1,77,1134,21,
345,Whitesboro Village,3733,4,0,,0,0,0,4,36,1,14,21,1,0
346,Whitestown Town,9141,0,0,,0,0,0,0,77,1,13,61,3,0
347,Woodbury Town,10685,3,0,,0,1,2,1,541,1,9,529,3,
348,Woodridge Village,829,7,0,,0,0,0,7,17,1,8,9,0,0
349,Woodstock Town,5931,2,0,,0,0,0,2,58,1,13,45,0,
350,Yonkers,199134,1036,6,,25,1,390,615,2368,1,470,1662,236,10
351,Yorktown Town,36643,15,0,,0,1,2,13,334,1,45,287,2,

## This code does not work.  Why?

robberies_binary = df['Robbery']
for item in robberies_binary:
    if item > 0:
        df['Robbery binary'] = 1
    elif item == 0:
        df['Robbery binary'] = 0

## This is a more elegent solution for converting df['Robbery'] to a series of binary values:

df['Robbery binary'] = df['Robbery'].apply(lambda x: 1 if x > 0 else 0)

df

In [106]:
df['Population Square'] = np.square(df['Population'])

In [107]:
df

,City,Population,Violent crime,Murder and non negligent manslaughter,Rape (revised definition) 1,Rape (legacy definition) 2,Robbery binary,Robbery,Aggravated assault,Property crime,Burglary binary,Burglary,Larceny theft,Motor vehicle theft,Arson 3,Population Square
4,Adams Village,1861,0,0,,0,0,0,0,12,1,2,10,0,0,3463321
5,Addison Town and Village,2577,3,0,,0,0,0,3,24,1,3,20,1,0,6640929
6,Akron Village,2846,3,0,,0,0,0,3,16,1,1,15,0,0,8099716
7,Albany,97956,791,8,,30,1,227,526,4090,1,705,3243,142,,9595377936
8,Albion Village,6388,23,0,,3,1,4,16,223,1,53,165,5,,40806544
9,Alfred Village,4089,5,0,,0,1,3,2,46,1,10,36,0,,16719921
10,Allegany Village,1781,3,0,,0,0,0,3,10,0,0,10,0,0,3171961
11,Amherst Town,118296,107,1,,7,1,31,68,2118,1,204,1882,32,3,13993943616
12,Amityville Village,9519,9,0,,2,1,4,3,210,1,16,188,6,1,90611361
13,Amsterdam,18182,30,0,,0,1,12,18,405,1,99,291,15,0,330585124
14,Arcade Village,2053,0,0,,0,0,0,0,39,1,3,35,1,0,4214809
15,Ardsley Village,4523,5,0,,0,1,3,2,33,1,4,28,1,0,20457529
16,Asharoken Village,658,0,0,,0,0,0,0,2,0,0,2,0,0,432964
17,Attica Village,2522,2,0,,0,0,0,2,5,0,0,4,1,0,6360484
18,Auburn,27270,96,1,,20,1,22,53,859,1,132,721,6,,743652900
19,Avon Village,3333,1,0,,0,1,1,0,25,1,3,20,2,,11108889
20,Baldwinsville Village,7473,5,0,,0,1,1,4,88,1,10,77,1,0,55845729
21,Ballston Spa Village,5418,8,0,,0,1,3,5,94,1,16,78,0,1,29354724
22,Batavia,15374,57,0,,7,1,13,37,559,1,103,454,2,,236359876
23,Bath Village,5733,15,0,,1,1,3,11,191,1,32,157,2,2,32867289
24,Bedford Town,17627,5,0,,0,1,1,4,156,1,26,127,3,,310711129
25,Bethlehem Town,34243,13,0,,0,1,3,10,442,1,50,388,4,,1172583049
26,Binghamton,46304,284,3,,19,1,101,161,2349,1,525,1767,57,,2144060416
27,Black River,1410,0,0,,0,0,0,0,14,1,2,12,0,0,1988100
28,Blooming Grove Town,12001,8,0,,1,0,0,7,99,1,20,72,7,,144024001
29,Bolivar Village,1022,1,0,,0,0,0,1,4,1,2,2,0,0,1044484
30,Bolton Town,2325,2,0,,0,0,0,2,24,1,4,20,0,0,5405625
31,Boonville Village,2054,1,0,,0,0,0,1,20,1,6,14,0,0,4218916
32,Brant Town,2065,4,0,,0,1,1,3,31,1,9,20,2,0,4264225
33,Brewster,2358,0,0,,0,0,0,0,13,1,3,10,0,0,5560164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,Tupper Lake Village,3642,3,0,,0,0,0,3,83,1,22,59,2,,13264164
323,Tuxedo Park Village,615,0,0,,0,0,0,0,0,0,0,0,0,0,378225
324,Ulster Town,12195,14,0,,3,1,2,9,437,1,25,410,2,,148718025
325,Utica,61686,361,7,,27,1,102,225,2528,1,449,1997,82,,3805162596
326,Vestal Town,27980,16,0,,2,1,6,8,571,1,39,523,9,,782880400
327,Walden Village,6887,18,1,,2,1,1,14,142,1,13,124,5,,47430769
328,Wallkill Town,27940,40,0,,3,1,16,21,767,1,91,650,26,1,780643600
329,Walton Village,3012,6,0,,1,0,0,5,68,1,18,50,0,,9072144
330,Warsaw Village,3453,6,0,,1,0,0,5,78,1,5,73,0,0,11923209
331,Washingtonville Village,5828,2,0,,0,1,1,1,58,1,5,51,2,0,33965584
332,Waterford Town and Village,8392,4,0,,0,0,0,4,59,1,6,52,1,0,70425664
333,Waterloo Village,5175,11,0,,0,1,3,8,194,1,23,169,2,,26780625
334,Watertown,28179,109,0,,12,1,16,81,1165,1,169,953,43,,794056041
335,Watervliet,10245,26,1,,3,1,11,11,242,1,58,163,21,,104960025
336,Watkins Glen Village,1862,6,0,,0,0,0,6,92,1,10,80,2,,3467044
337,Waverly Village,4337,5,0,,0,1,1,4,54,1,9,41,4,,18809569
338,Webster Town and Village,43777,21,0,,2,1,3,16,469,1,101,361,7,,1916425729
339,Weedsport Village,1797,0,0,,0,0,0,0,25,1,5,20,0,0,3229209
340,Wellsville Village,4574,11,0,,1,0,0,10,164,1,32,129,3,1,20921476
341,Westhampton Beach Village,1732,2,0,,0,0,0,2,44,1,4,37,3,0,2999824
342,West Seneca Town,44821,35,1,,1,1,9,24,896,1,166,710,20,0,2008922041
343,Whitehall Village,2604,6,0,,0,0,0,6,62,1,12,49,1,,6780816
344,White Plains,57559,78,1,,3,1,28,46,1232,1,77,1134,21,,3313038481
345,Whitesboro Village,3733,4,0,,0,0,0,4,36,1,14,21,1,0,13935289
346,Whitestown Town,9141,0,0,,0,0,0,0,77,1,13,61,3,0,83557881
347,Woodbury Town,10685,3,0,,0,1,2,1,541,1,9,529,3,,114169225
348,Woodridge Village,829,7,0,,0,0,0,7,17,1,8,9,0,0,687241
349,Woodstock Town,5931,2,0,,0,0,0,2,58,1,13,45,0,,35176761
350,Yonkers,199134,1036,6,,25,1,390,615,2368,1,470,1662,236,10,39654349956
351,Yorktown Town,36643,15,0,,0,1,2,13,334,1,45,287,2,,1342709449